### PR TITLE
Fixes #97

### LINKED ISSUE #97: Data is returned as elements of processed array (not as objects inside it)
When submitting a query like the following:
```
{
  "objectType":"country",
  "version":"1.0.0",
  "projection": [ 
    { "field" : "iso2code", "include" :  true},
  ],
  "query" : { "field":"iso2code","op":"=","rvalue":"US" }
}
```
I am receiving a response that contains the value of the projection I am asking for as an element of the processed array (and the matchCount is off it seems)
```
{
  "status" : "COMPLETE",
  "processed" : [
    "US"
  ],
  "modifiedCount" : 0,
  "matchCount" : 0
}
```
What I would expect to see is something like this, where the field I asked for is included in an object inside the processed array (with the correct match count).
```
{
  "status" : "COMPLETE",
  "processed" : [
    {
      "iso2code" : "US"
    }
  ],
  "modifiedCount" : 0,
  "matchCount" : 1
}
```

### PR DESCRIPTION
**Pull request by luan-cestari**
Fix the problem of array with only values returned described in issue #97

### CODE REVIEW

**Comment by bserdar** [comment]
The handling of arrays is not correct. According to the code, if there is an array with one element in it, it'll be translated as a value. All other arrays are translated as arrays of string. That means, object arrays are not supported by this translation or any other type of simple data.

**Comment by jewzaam** [comment]
There are no unit tests added for this PR.  We need to verify issues are fixed with tests.

**Comment by luan-cestari** [comment]
Created some tests

**Comment by luan-cestari** [comment]
@bserdar about the handling the arrays, do you think it would be correct to make a recursive fuction that would enable embed objects inside of another embed object ?

**Comment by bserdar** [comment]
That's possible, but it'll depend on how you organized data on entry. If
the RDBMS data are in a form that can be processed recursively, then you
can do that.

**Pull request merged**
