### PR TITLE
Fixes #75

### LINKED ISSUE #75: Licensing Issue with NamedParameterStatement
At a glance much of the implementation is copied from

https://github.com/bnewport/Samples/blob/master/wxsutils/src/main/java/com/devwebsphere/jdbc/loader/NamedParameterStatement.java

which looks to have a non-permissive license
https://github.com/bnewport/Samples/blob/master/wxsutils/LICENSE
```
This sample program is provided AS IS and may be used, executed, copied and
modified without royalty payment by customer (a) for its own instruction and 
study, (b) in order to develop applications designed to run with an IBM 
WebSphere product, either for customer's own internal use or for redistribution 
by customer, as part of such an application, in customer's own products. "

5724-J34 (C) COPYRIGHT International Business Machines Corp. 2009
All Rights Reserved * Licensed Materials - Property of IBM
```
You could switch to use this one... https://github.com/colloquium/spacewalk/blob/d4bee4ec00fc89e00dd5c74a684298ebf0e2f686/java/code/src/com/redhat/rhn/common/db/NamedPreparedStatement.java
Looks like a new implementation under GPLv2

### PR DESCRIPTION
**Pull request by luan-cestari**
This PR aims to fix #75

### CODE REVIEW

**Comment by bserdar** [comment]
In general, I don't think this is a good idea. All this class does is giving the ability to specify names in metadata instead of argument indexes, and in my opinion, we can live without it. Parsing the SQL query is not a good idea, especially if the parsed query is doing string manipulation. That said, there are some problems with the parser:

 - The parser cannot deal with escaped quotes, 
 - The parser cannot deal if : or ' is used as an escape in LIKE
 - parser fails if : is the last character 
 - parser assumes anything that starts with : is a variable

Also, pls rebase from master

**Comment by luan-cestari** [comment]
I think I can fix the issues and this feature is nice to have, specially to simplify the user wor, but I agree that SQL manipulation can be dangerous (SQL-Injection)

**Comment by luan-cestari** [comment]
Created some tests to increase the coverage and fold some cases that it would be wrong (they are a bit complex but they are valid). 

@bserdar From the possible problems you mentioned, only the "parser fails if : is the last character" I didn`t get it . A SQL statement that ends with a : would be malformed. Could you give me an example the syntax is correct but would lead to an error please? Also, I updated the PR.

**Comment by bserdar** [comment]
If the last character is a :, the parser fails with an "array index out of
bounds" exception, instead of a malformed sql statement exception.

**Comment by luan-cestari** [comment]
You are right @bserdar . Pushed a fix for that. Let me know if you want me to handle that in a different way

**Comment by luan-cestari** [comment]
I also think that after we finish we could push a PR for spacewalk which have the same flaws as we had

**Comment by jewzaam** [comment]
@luan-cestari open an issue if nothing else..

**Comment by luan-cestari** [comment]
@jewzaam done, the issue is https://github.com/colloquium/spacewalk/issues/1

**Comment by bserdar** [comment]
Your quote logic is wrong. You can't do what you're trying to do without a stack. It won't parse this:

 ' 123 "123"123 '

Why are you even working with double quotes?

Also, there is no way to deal with this:

select * from table where column like 'abc:%def%' escape ':'

These kind of edge cases are the reason why I am against parsing sql statements.

**Comment by luan-cestari** [comment]
I just pushed new test scenarios following what you mentioned but I didn't find any issue. So you can check them out and see if it is fine that way or not.

I think we can also make the edge cass more clear, so we could define each edge case and make a specific test for it.

**Comment by bserdar** [comment]
How about this:

select * from table where column like ' 123 \"123\"1 :xyz 23 '

I believe it will parse :xyz as a field.

**Comment by luan-cestari** [comment]
@bserdar I just pushed a new test and it worked fine. Any other suggestions?

**Pull request merged**
