### PR TITLE
Fixes issue #102 (tests included)

### LINKED ISSUE #102: java.sql.Date to Timestamp Conversion error
When retrieving a date field from RDBMS entity, the following error occurs

2015-01-26 15:54:16,005 [hystrix-FindCommand-9] ERROR [com.redhat.lightblue.util.Error] java.util.Date cannot be cast to java.sql.Date: java.lang.ClassCastException: java.util.Date cannot be cast to java.sql.Date
	at com.redhat.lightblue.metadata.rdbms.converter.RDBMSUtilsMetadata.processDynVar(RDBMSUtilsMetadata.java:176)
	at com.redhat.lightblue.metadata.rdbms.converter.RDBMSUtilsMetadata.getStatement(RDBMSUtilsMetadata.java:124)
	at com.redhat.lightblue.metadata.rdbms.converter.RDBMSUtilsMetadata.buildAllMappedList(RDBMSUtilsMetadata.java:219)
	at com.redhat.lightblue.hystrix.rdbms.ExecuteSQLCommand.run(ExecuteSQLCommand.java:74)
	at com.redhat.lightblue.hystrix.rdbms.ExecuteSQLCommand.run(ExecuteSQLCommand.java:31)
	at com.netflix.hystrix.HystrixCommand$HystrixCommandFromObservableCommand$1.call(HystrixCommand.java:355)
	at com.netflix.hystrix.HystrixCommand$HystrixCommandFromObservableCommand$1.call(HystrixCommand.java:350)
	at rx.Observable$2.call(Observable.java:173)
	at rx.Observable$2.call(Observable.java:166)
	at rx.Observable.unsafeSubscribe(Observable.java:8587)
	at com.netflix.hystrix.HystrixObservableCommand$4.call(HystrixObservableCommand.java:419)
	at com.netflix.hystrix.HystrixObservableCommand$4.call(HystrixObservableCommand.java:405)
	at rx.Observable.unsafeSubscribe(Observable.java:8587)
	at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69)
	at com.netflix.hystrix.strategy.concurrency.HystrixContextScheduler$ThreadPoolWorker$1.run(HystrixContextScheduler.java:165)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

### PR DESCRIPTION
**Pull request by luan-cestari**
This pR aims to fix #102

### CODE REVIEW

**Comment by bserdar** [comment]
The part in processDynVar

+ } else if (o instanceof java.sql.Date) {

is unnecessary. java.sql.Date extends java.util.Date, that block will never execute

**Comment by bserdar** [comment]
This is also probably related to #73. You are not using metadata type information while processing fields.

**Comment by luan-cestari** [comment]
@bserdar Fixed the point of code about Date you mentioned. About #73, I think  this PR is for the #102  , so the changes #73 should be another PR (maybe it will depend  on the changes of this PR, but either way, we check the consistency of the PR for the issue it aims to solve (not all the issues the project have or will have) )

**Comment by luan-cestari** [comment]
@derek63 @bserdar this PR pending to be merged to fix issue #102 (IDK if you guys saw that one of jobs failed but if you see the log it showed that it was a problem fetching one jar due timeout. that problem occurs time to time in different branches, for your information (as you can encounter this issue again))

**Pull request merged**
